### ISSUE TITLE
Adjust Position of Tooltip to Prevent Overflow

### ISSUE THREAD

**Issue by cjhowald** [zalando/dress-code#157]
In some cases the tooltip will overflow the layout (even when hidden), causing visual issues.

![image](https://cloud.githubusercontent.com/assets/14326547/13947467/0e9f90f6-f01b-11e5-956f-fae73c9feebf.png)

Since the dress code can't know where and how the tooltips appear relative to the layout, it would be nice to have an easy way to control the position.

For now, the workaround is to override the position of the arrow and/or bubble directly as needed.

```css
  .dc-has-tooltip:after {
    left: 6px;
  }
  .dc-has-tooltip:before {
    left: -120px;
  }
```

![image](https://cloud.githubusercontent.com/assets/14326547/13947584/ace967aa-f01b-11e5-88b2-378bd50373b0.png)

This works, but is not very elegant or transparent for users of the library.
