### ISSUE TITLE
Opacity of messages

### ISSUE THREAD

**Issue by bzums** [zalando/dress-code#250]
Currently the messages have different opacities:
`info`, `warning` and `error`: 0.5
`succes` 0.95

Is there are reason to use opacity there at all?
For example the toasts do not use it.

The problem is that we show messages over other content and with `success` everything is fine but with the other classes the message is really bad to read caus of the opacity. 

And I do not know a way how to override just the opacity of the element, for example the `dc-msg--warning` looks like:
```css
.dc-msg--warning {
    border-color: #ebc600;
    background: rgba(255, 240, 158, 0.5);
    color: #99840e;
}
```
Is there a way to overwrite just the alpha property for this class?

Best
