### ISSUE TITLE
Hide native browser clear button in "date" field

### ISSUE THREAD

**Issue by LeoAref** [zalando/dress-code#309]
Currently if we have search form with input field of type "date", two clear buttons will appear (native, and dress-code), so we need to remove the native one

#### Current state:

![pasted image 0](https://cloud.githubusercontent.com/assets/6577222/21931972/8d4d2c7a-d99e-11e6-9122-dc3837104fb4.png)

#### Suggested solution:
```css
:-webkit-clear-button {
  display: none;
}
```
