### ISSUE TITLE
Make some space for sorting arrows.

### ISSUE THREAD

**Issue by SergKam** [zalando/dress-code#348]
Sometimes, table header with sorting arrows looks broken. See 
![bug2](https://cloud.githubusercontent.com/assets/3240529/25289996/4ae17e4c-26cc-11e7-879b-3a780b13c979.png)
 
The fix is simple like
```css
.dc-table__th--sortable {
    padding-right: 20px;
}
```
Also, I don't think someone would need a multiline header, especially with sorting (it looks bad).
![bug3](https://cloud.githubusercontent.com/assets/3240529/25290215/45e75a50-26cd-11e7-8a34-6ad2f6ed6d35.png)

I would suggest to disable it.
```css
.dc-table__th {
    white-space: nowrap;
}
```
