### ISSUE TITLE
Add error state for a textarea.

### ISSUE THREAD

**Issue by SergKam** [zalando/dress-code#349]
As an input, a textarea field sometimes needs validation and as a result the error state.
I expect it to be some thing like this in the end.
```css
.dc-textarea--is-error,
.dc-textarea--is-error:hover,
.dc-textarea--is-error:focus {
    border-color: #ff4a25;
}
```
![bug4](https://cloud.githubusercontent.com/assets/3240529/25290684/4d387b98-26cf-11e7-8aa9-1f202a39a3aa.png)
