### ISSUE TITLE
Namespace all classes, avoid styling native elements directly

### ISSUE THREAD

**Issue by rbarilani** [zalando/dress-code#7]
To avoid css conflicts. We need to namespace all css classes and never apply styling directly to native elements.

EXAMPLE:

``` css
/* NO */
button {
    width:100px;
    color: blue; 
}

/* YES */
.hb-btn {
   width:100px;
    color: blue; 
}
```
